services:

  frontend:
    build: 
      context: ./tiny-pulse-frontend
    networks:
      - appnet
    ports:
      - "4000:80"
    depends_on:
      - backend
  backend:
    build: 
      context: ./tiny-pulse-backend
    
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER:-tiny-pulse}
      DB_NAME: ${POSTGRES_DB:-tiny-pulse}
      DB_POOL_SIZE: 10
      DB_MAX_OVERFLOW: 20
    secrets:
      - db-password
    networks:
      - appnet
    ports:
      - "4567:80"
    
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-tiny-pulse}
      POSTGRES_DB: ${POSTGRES_DB:-tiny-pulse}
    secrets:
      - db-password
    networks:
      - appnet
    volumes:
      - pg_data:/var/lib/postgresql/data
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER:-default_user} -d $${POSTGRES_DB:-default_db}"]
      interval: 5s
      timeout: 5s
      retries: 5


secrets:
  db-password:
    file: ./secrets/db-password.txt

networks:
  appnet:
    name: appnet

volumes:
  pg_data: