[project]
name = "tiny-pulse-backend"
version = "0.1.0"
description = "FastAPI backend"
readme = "README.md"
authors = [
    { name = "Keshav Tangri", email = "tangri57@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "asyncpg>=0.31.0",
    "fastapi[standard]>=0.141.1",
    "httpx>=0.28.1",
    "psycopg2-binary>=2.9.12",
    "pydantic>=2.13.4",
    "sqlalchemy>=2.0.52",
]

[tool.uv]
package = false

[tool.fastapi]
entrypoint = "app.main:app"
